### PR TITLE
Added random state in RF classifier

### PR DESCRIPTION
**Pull request by shubham7jain**

### CODE REVIEW

**Review by navgupta14 — COMMENTED** [review]
How did you decide on this value ? Is this some seed ?

**Comment by shubham7jain** [comment]
No I just use some value that was mentioned in that article. It may not be the optimal. But atleast using that, results are not changing.

**Comment by navgupta14** [comment]
ok cool, I'll merge it tomorrow.

**Comment by navgupta14** [comment]
Yeah, its the seed to generate random number.

**Pull request merged**
