### PR TITLE
Making Changes as per the new data

### PR DESCRIPTION
**Pull request by shubham7jain**

### CODE REVIEW

**Comment by shubham7jain** [comment]
1. Fixed deprecation warning
2. Partition code as per new data format as time is now coming in seconds
3. Partition made 1000 times faster by using binary search in the intersection. Earlier partition was taking more than an hour long for Chicago data, now just some seconds.

**Review by navgupta14 — APPROVED** [review]
its great, but do we need it ?. I mean if its taking long for big data ?

**Comment by shubham7jain** [comment]
Yeah as I mentioned earlier, it was taking way too long in the intersection method, so it was really needed. Earlier for each call of intersection, it was taking 3-4 ms and now 3-4 micro seconds.

**Comment by navgupta14** [comment]
cool

**Comment by adityangud** [comment]
Woah. Nice. 👍

**Pull request merged**
