### PR TITLE
Revert "Merge pull request #62 from navgupta14/master"

### PR DESCRIPTION
**Pull request by navgupta14**
This reverts commit 10d7328654cb29397b06231922635d4058bd76e9, reversing
changes made to 499bd3ceab41729911aa29a568067852fe03b0a4.

### CODE REVIEW

**Comment by shubham7jain** [comment]
Bhai ye kya ho rha hai itne reverts :P

**Comment by shubham7jain** [comment]
Don't merge this ..

**Comment by adityangud** [comment]
Are we not merging this?

**Comment by navgupta14** [comment]
It is fine now ?

**Comment by shubham7jain** [comment]
Cool sirji 👍

**Pull request merged**
